name: PR
on: [pull_request]
jobs:
  build:
    # TODO: Ideally this could *actually* build production-ready files. Maybe for Sprint 2?
    runs-on: ubuntu-latest
    steps:
      - name: Chekout Repository
        uses: actions/checkout@v3

      - name: Install Node.JS v18 For Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Check Frontend Build
        run: |
          cd frontend
          npm ci
          tsc --noEmit

      - name: Install Node.JS v18 For Backend
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Check Backend Build
        run: |
          cd backend
          npm ci
          tsc --noEmit

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - run: npm ci
        
      - name: Run Prettier Check
        run: npm run prettier:check

      - name: Run ESLint
        run: npm run lint
  tests:
    needs: build
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Chekout Repository
        uses: actions/checkout@v3

      - name: Install Node.JS v18 For Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Run Frontend Tests
        run: |
          cd frontend
          npm ci
          npm test
          cd ..

      - name: Install Node.JS v18 For Backend
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Run Backend Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd backend
          npm ci
          npm test
