name: PR
on: [pull_request]
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout Repository
      uses: actions/checkout@v3

    - run: cd frontend
    
    - name: Install Node.JS v18 For Frontend
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Run Frontend Tests
      run: |
        npm ci
        npm test
        cd ..
  
    - run: cd backend
    
    - name: Install Node.JS v18 For Backend
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Run Backend Tests
      run: |
        npm ci
        npm test