name: PR
on: [pull_request]
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout Repository
      uses: actions/checkout@v3

    - name: Install Node.JS v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Run Frontend Tests
      run: |
        cd frontend
        npm ci
        npm test
        cd ..

    - name: Run Backend Tests
      run: |
        cd backend
        npm ci
        npm test